#!/usr/bin/env python3
import itertools, operator, re, sys

operators = tuple(zip((operator.add, operator.sub, operator.mul, operator.truediv), '+-*/'))
inputs = [int(i) for i in re.findall('\S+', sys.stdin.readline())]
for perm in itertools.permutations(inputs[:-1]):
    for ops in itertools.product(operators, repeat=len(inputs)-2):
        val = perm[0]
        for x, op in zip(perm[1:], ops):
            val = op[0](val, x)
        if val == inputs[-1]:
            print(' '.join('%d %s' % (n, o[1]) for n, o in zip(perm[:-1], ops)),
                  perm[-1], '=', inputs[-1])
            sys.exit()
print('Invalid')
